# 7월 2일 (금요일) 필기

----

In [4]:
import numpy as np
import tensorflow as tf
import pandas as pd

In [70]:
import torch

### Element wise 연산

In [28]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [29]:
a+b

array([5, 7, 9])

넘파이는 element wise 연산을 해준다.

In [14]:
[1,2,3]+[4,5,6]

[1, 2, 3, 4, 5, 6]

In [31]:
@np.vectorize
def x(a,b):
    return a+b
x(a,b)

array([5, 7, 9])

In [32]:
shape 이 안맞으면 연산이 안맞는다 - element wise 이기 때문에!

array([5, 7, 9])

### Broadcasting

In [35]:
a+1

array([2, 3, 4])

기본적으로 모양이 같아야 연산할 수 있지만 위처럼 출력이 된다 - broadcasting

피연산대상의 shape으로 자동적으로 맞춰주는것. [1,1,1] 이란 array 로 바뀐다! - 이게 broadcasting.

In [37]:
a>1

array([False,  True,  True])

In [44]:
b = np.array([1,2])
b

array([1, 2])

In [40]:
c = np.array([[1,2],[3,4]])
c

array([[1, 2],
       [3, 4]])

In [45]:
c + b

array([[2, 4],
       [4, 6]])

broadcasting 하면 b 는 [[1,2],[1,2]] 로 복사가 되는 느낌이다!

In [48]:
d = np.array([[1],[2]])
d

array([[1],
       [2]])

In [49]:
c+d

array([[2, 3],
       [5, 6]])

d 가 stretch 연산이 되며 c 의 shape 으로 바뀌어서 연산이 된다!

-------

In [54]:
b

array([1, 2])

In [55]:
d

array([[1],
       [2]])

In [56]:
b+d

array([[2, 3],
       [3, 4]])

이게 어떻게 되는걸까? 그냥 아래로, 밑으로 확장되서 더해지는거다~

broadcasting 방식은 Less basic 하다.

indexing, slicing 방법은 총 5개.

그중 fancy indexing 은 advanced indexing!

----------

### Tensorflow

In [65]:
x = tf.constant([1,2,3])
x

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [66]:
x+1

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 3, 4], dtype=int32)>

텐서플로우도 broadcasting 지원을 한다!

In [72]:
b = torch.tensor([1,2,3])
b

tensor([1, 2, 3])

In [73]:
b+1

tensor([2, 3, 4])

파이토치도 broadcasting 지원을 한다!

In [75]:
a = np.array([[1,2],[3,4]])
b = np.array([[1,2],[3,4]])

In [76]:
a*b

array([[ 1,  4],
       [ 9, 16]])

기본적으로 연산은 elementwise 연산이다. 각 위치별 element 끼리 곱한다.

그러면 행렬 연산자는 없을까?

In [78]:
a@b

array([[ 7, 10],
       [15, 22]])

넘파이에선 다른 연산자에서 쓸수없는 @연산자가 있다! 행렬곱!

In [80]:
np.multiply(a,b)

array([[ 1,  4],
       [ 9, 16]])

In [81]:
np.dot(a,b)

array([[ 7, 10],
       [15, 22]])

multiply 함수는 element wise 곱이고

dot 함수는 행렬 곱이다!

dot() 을 써도 되고 @ 을 써도 된다~

In [83]:
a.dot(b)

array([[ 7, 10],
       [15, 22]])

이렇게 메서드 방식으로도 할 수 있다.

-----

넘파이는 기본적으로 함수방식을 사용한다.

In [90]:
c = np.array ([1,2,3])
d = np.array ([1,2,3])

In [91]:
np.dot(c,d)

14

shape 에 따라서 이 연산결과가 다를 수 있다.

------

### Matrix

In [98]:
k = np.matrix([[1, 2], [3, 4]])
k

matrix([[1, 2],
        [3, 4]])

넘파이는 기본적으로 array, matrix 둘다 정의해준다!

In [102]:
j = np.matrix([[1, 2], [3, 4]])
j

matrix([[1, 2],
        [3, 4]])

In [103]:
np.dot(k,j)

matrix([[ 7, 10],
        [15, 22]])

In [104]:
np.multiply(k,j)

matrix([[ 1,  4],
        [ 9, 16]])

In [105]:
k@j

matrix([[ 7, 10],
        [15, 22]])

In [106]:
k*j

matrix([[ 7, 10],
        [15, 22]])

In [107]:
a*b

array([[ 1,  4],
       [ 9, 16]])

어레이랑 메트릭스랑 연산방식이 다르기 때문에 잘 숙지해라!!

작은 데이터구조일수록 느린 경우가 있다. 왜?

In [110]:
np.lookfor('sum')

Search results for 'sum'
------------------------
numpy.sum
    Sum of array elements over a given axis.
numpy.cumsum
    Return the cumulative sum of the elements along a given axis.
numpy.einsum
    einsum(subscripts, *operands, out=None, dtype=None, order='K',
numpy.nansum
    Return the sum of array elements over a given axis treating Not a
numpy.nancumsum
    Return the cumulative sum of array elements over a given axis treating Not a
numpy.einsum_path
    Evaluates the lowest cost contraction order for an einsum expression by
numpy.trace
    Return the sum along diagonals of the array.
numpy.ma.sum
    Return the sum of the array elements over the given axis.
numpy.polyadd
    Find the sum of two polynomials.
numpy.ma.cumsum
    Return the cumulative sum of the array elements over the given axis.
numpy.logaddexp
    Logarithm of the sum of exponentiations of the inputs.
numpy.matrix.sum
    Returns the sum of the matrix elements, along the given axis.
numpy.logaddexp2
    Logarit

ufunc = universial function 의 줄임말.

In [112]:
np.add([1,2,3],[1,2,3])

array([2, 4, 6])

add 는 속도가 굉장히 빠르다.

파이썬에 있는 모든 수학관련 펑션은 ufunc에 있다.

In [114]:
a.strides

(16, 8)

In [116]:
a = np.arange(24).reshape(12,2)
a

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [117]:
a.sum(axis=0)

array([132, 144])

In [118]:
a.sum(axis=1)

array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37, 41, 45])

In [120]:
a.shape

(12, 2)

In [121]:
a.mean(axis=1)

array([ 0.5,  2.5,  4.5,  6.5,  8.5, 10.5, 12.5, 14.5, 16.5, 18.5, 20.5,
       22.5])

In [122]:
a.mean(axis=0)

array([11., 12.])

------

------

------

In [126]:
import tensorflow as tf

In [127]:
(X_train,y_train),(X_test,y_test) = tf.keras.datasets.mnist.load_data()

In [128]:
import numpy.ma as mnp

In [129]:
import numpy as np

In [130]:
np.unique(y_train,return_counts = True)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8),
 array([5923, 6742, 5958, 6131, 5842, 5421, 5918, 6265, 5851, 5949]))

In [131]:
import seaborn as sns

In [132]:
mpg = sns.load_dataset('mpg')

In [134]:
mpg.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64  
 2   displacement  398 non-null    float64
 3   horsepower    392 non-null    float64
 4   weight        398 non-null    int64  
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64  
 7   origin        398 non-null    object 
 8   name          398 non-null    object 
dtypes: float64(4), int64(3), object(2)
memory usage: 28.1+ KB


In [136]:
mpg.horsepower.size

398

In [140]:
mpg.horsepower.count()

392

size 와 count는 정확하게 구분해야 한다. 카운트는 미싱데이터 관점에서 계산을 한다. 그럼 여기서 미싱데이터는 총 6개.

------


In [152]:
a = np.arange(24)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [153]:
a.shape

(24,)

차원을 바꾼다는 것은 기본적으로 shape 을 바꾸는거다.

In [154]:
a.reshape(4,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [ ]:
shape을 바꾼다는 건 내부적으로 stride를 바꾸는거다.

In [155]:
a.reshape(3,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [156]:
a.reshape(2,4,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [157]:
a.reshape(2,4,3,1,1,1,1,1,1)

array([[[[[[[[[ 0]]]]]],





         [[[[[[ 1]]]]]],





         [[[[[[ 2]]]]]]],






        [[[[[[[ 3]]]]]],





         [[[[[[ 4]]]]]],





         [[[[[[ 5]]]]]]],






        [[[[[[[ 6]]]]]],





         [[[[[[ 7]]]]]],





         [[[[[[ 8]]]]]]],






        [[[[[[[ 9]]]]]],





         [[[[[[10]]]]]],





         [[[[[[11]]]]]]]],







       [[[[[[[[12]]]]]],





         [[[[[[13]]]]]],





         [[[[[[14]]]]]]],






        [[[[[[[15]]]]]],





         [[[[[[16]]]]]],





         [[[[[[17]]]]]]],






        [[[[[[[18]]]]]],





         [[[[[[19]]]]]],





         [[[[[[20]]]]]]],






        [[[[[[[21]]]]]],





         [[[[[[22]]]]]],





         [[[[[[23]]]]]]]]])

즉, reshape 했을 때 곱해서 24만 나오면 되기 때문에 1을 곱해서 차원을 무한대로 늘릴 수 있다.

In [160]:
a.reshape(3,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [162]:
a.resize(4,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [163]:
a = a.resize(3,8)

In [166]:
print(a)

None


왜 none 이지?

자기 자신은 바뀌었지만 리턴값이 없었기 때문에 None이 되는것..

reshape 과 resize 의 차이?

-----

In [172]:
a = np.arange(24).reshape(3,8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [174]:
tips = sns.load_dataset('tips')

In [175]:
tips

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [177]:
tips.drop(columns = 'day') #immutable 방식

total_bill   tip     sex smoker    time  size
0         16.99  1.01  Female     No  Dinner     2
1         10.34  1.66    Male     No  Dinner     3
2         21.01  3.50    Male     No  Dinner     3
3         23.68  3.31    Male     No  Dinner     2
4         24.59  3.61  Female     No  Dinner     4
..          ...   ...     ...    ...     ...   ...
239       29.03  5.92    Male     No  Dinner     3
240       27.18  2.00  Female    Yes  Dinner     2
241       22.67  2.00    Male    Yes  Dinner     2
242       17.82  1.75    Male     No  Dinner     2
243       18.78  3.00  Female     No  Dinner     2

[244 rows x 6 columns]

데이칼럼은 안보이지만 살아있긴 하다!

In [179]:
tips.drop(columns = 'day', inplace=True) #mutable 방식

In [180]:
tips

total_bill   tip     sex smoker    time  size
0         16.99  1.01  Female     No  Dinner     2
1         10.34  1.66    Male     No  Dinner     3
2         21.01  3.50    Male     No  Dinner     3
3         23.68  3.31    Male     No  Dinner     2
4         24.59  3.61  Female     No  Dinner     4
..          ...   ...     ...    ...     ...   ...
239       29.03  5.92    Male     No  Dinner     3
240       27.18  2.00  Female    Yes  Dinner     2
241       22.67  2.00    Male    Yes  Dinner     2
242       17.82  1.75    Male     No  Dinner     2
243       18.78  3.00  Female     No  Dinner     2

[244 rows x 6 columns]

리턴값이 있냐 없냐에 따라 뮤터블, 임뮤터블로 사용 할 수 있다.

In [183]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [185]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

flatten으로 우아하게 1차원 데이터로 만들 수 있다!!

In [187]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

ravel 은 flatten과 같아보이지만 분명 차이점이 있다.

ravel이 더 빠르다. 출력값은 없지만 ravel 로 통해 수정한 어레이를 수정하면 기존 어레이도 함께 수정된다.
flatten 은 객체를 복사해준다.
------
flatten = copy

ravel = view

이렇게 외워라!

---------

In [202]:
a = np.array([2,0,2,1])
a

array([2, 0, 2, 1])

In [199]:
a[np.newaxis,:]

array([[2, 0, 2, 1]])

In [204]:
a[:,np.newaxis]

array([[2],
       [0],
       [2],
       [1]])

In [206]:
a = np.arange(24).reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [208]:
np.swapaxes(a,1,2)

array([[[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]],

       [[12, 16, 20],
        [13, 17, 21],
        [14, 18, 22],
        [15, 19, 23]]])

shape 을 바꾸는 무궁무진한 방법.. 다 알아야한다ㅠ
newaxis, swapaxes 등등..

------

In [214]:
import torch as th

In [215]:
import tensorflow as tf

In [216]:
tf.expand_dims

<function tensorflow.python.ops.array_ops.expand_dims_v2(input, axis, name=None)>

In [217]:
th.moveaxis

<function _VariableFunctionsClass.moveaxis>

In [218]:
x = np.arange(6).reshape(2,3)
y = np.arange(6,12).reshape(2,3)

In [219]:
x

array([[0, 1, 2],
       [3, 4, 5]])

In [220]:
y

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [234]:
np.concatenate((x,y), axis = 0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [235]:
np.concatenate((x,y), axis = 1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [237]:
np.stack((x,y), axis = 0)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [238]:
np.concatenate((x,y), axis = 0).shape

(4, 3)

In [239]:
np.stack((x,y), axis = 0).shape

(2, 2, 3)

어레이를 붙히는 방법들이 많다!

----------

판다스는 무조건 2차원 데이터밖에 없기 때문에 붙히는 방법이 조금 다르다!

In [243]:
import seaborn as sns

In [249]:
iris = sns.load_dataset('iris')

In [252]:
iris

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

-----

넘파이는 비슷비슷한게 정말 많다.

In [255]:
x

array([[0, 1, 2],
       [3, 4, 5]])

In [256]:
y

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [257]:
np.concatenate((x,y), axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [258]:
np.vstack((x,y))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [260]:
np.hstack((x,y))

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

vstack 은 axis = 0: vertical
hstack 은 axis = 1: horizontal

In [262]:
np.dstack((x,y))

array([[[ 0,  6],
        [ 1,  7],
        [ 2,  8]],

       [[ 3,  9],
        [ 4, 10],
        [ 5, 11]]])

In [263]:
np.column_stack((x,y))

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [264]:
np.row_stack((x,y))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

똑같은게 왜이렇게 많지?

In [266]:
np.r_[x,y]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [267]:
np.s_[1:]

slice(1, None, None)

----------